language: r
cache: packages
pandoc_version: 2.9.2.1
addons:
  apt:
    packages:
    - ghostscript
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: CJ9OHkDvo7AKhodxB4H0JOToMZb2Z0XNGzo+sk4gPjX4BfR40w7EMZmjmPtrCe5gJmbvkoUNm5uTxCAjmi13AbdbepoROLyT/Ki7JuQzWMJMH7qbw2WR0zqVhBPFl96n6Am4W61G/VPvJz1LiH8sN4cf+1Qf3xE0RqQkPPcB50x58lZvBoIwdVuuIWE+i6YOpOCi5+q5tT7XBTK6ik/h+dsXckg5SMAh24SyGGasjfhBG0fEnsWuxv2bL+ToCb2OXAdegtfrMKlrYmqz/mQAhmQn3Xq8YA/hZrbG/f8VN+ZPSASY7JhUImf/8wbaMuZlszDSg/V2Asuu1hGm+CPYBo9pDy5ta+s3mQMV2S4AZcENXaLkTqK6XCki3XPYU+RqpRXze3R00thhW9zyLs5Khu9bz+vVA9f/vSNBnquCNq/TbKy3qVHLmrh7KFcDx9j7tW3/9dEkXKCpl9GtBGzMsxi+QJU4TvKcI8uZgEJhQVr6eLHWwk6wTzwiiuqdfWAu0I0NEOcH4yZCG0XT/6HBrveWcE+JY63pbfeJ/2WvfA3a6DanywzmCIb0EB6+TtiDiUwcWWKsuf/zXr+tQl/zx0Q0vq+3bwnGxYDkMFjsuBNtw0beAjDPLU4Vfv9s9dHjkE1tcOb6Io76GDqh/XTgX5gMhh3l0zSW/qQiDE1kLqA=
